# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A7kEHdM866nipAK-r05aLlEBXp0SxvHm
"""

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

cd My Drive

import sys
import argparse
import cv2
import os

import cv2

print(cv2.__version__)


def extractImages(pathIn, pathOut):
    count = 0
    vidcap = cv2.VideoCapture(pathIn)
    while True:
        success, image = vidcap.read()
        if success:
            vidcap.set(cv2.CAP_PROP_POS_MSEC, (count * 1000))  # added this line
            print('Read a new frame: ', success)
            cv2.imwrite(pathOut + "\\frame%d.jpg" % count, image)  # save frame as JPEG file
            count = count + 1
        else:
            vidcap.release()
            cv2.destroyAllWindows()
            break


if __name__ == "__main__":
    print("aba")
    pathIN = "onemin.mp4"  # C:\\Users\\Ekansh\\Desktop\\python\\API-master\\onemin.mp4
    pathOUT = "img/"  # "C:\\Users\\Ekansh\\Desktop\\python\\API-master\\img"
    extractImages(pathIN, pathOUT )

